---
title: "Morro Bay Seine Analyses"
author: "Maurice Goodman"
date: "Updated October 2020"
output: pdf_document
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(checkpoint)
checkpoint("2020-09-01")

library(here)
source(here("R", "packages.R"))

knitr::opts_chunk$set(fig.height = 6, fig.width = 10, message = FALSE, warning = FALSE)
options(knitr.kable.NA = '')

source(here("R", "cluster_bootstrap.R"))

theme_trawls <- theme_classic() +
  theme(axis.line.x = element_line(size = 1), 
        axis.line.y = element_line(size = 1), 
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "lines"),
        strip.background = element_blank(),
        axis.text = element_text(size = 14, color = "black"),
        axis.title = element_text(size = 16, face = "bold"),
        strip.text = element_text(size = 18, face = "bold", margin = margin(0,0,4,0)),
        legend.text = element_text(size = 14, margin = margin(0, 4, 0, 4)), 
        legend.title = element_text(size = 14, face = "bold"),
        strip.placement = "outside")

capitalize <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1, 1)), substring(s, 2),
        sep = "", collapse = " ")
}
```

# Metadata

## Sample Size Breakdown
```{r sample_size}
seine_data <-
  read_csv(here("data", "seine_fish_data.csv")) %>%
  filter(year == 2017 | year == 2018) %>% 
  mutate(year = factor(year, levels = c("2017", "2018"), ordered = TRUE)) %>% 
  filter(site_name %in% c("Windy Cove", "Colemans")) %>% 
  mutate(date = as.Date(date, format = "%m/%d/%Y"), 
         spec_binomial = paste(genus, species, sep = " "),
         spec_binomial = dplyr::recode(spec_binomial, "Sebastes NA" = "Sebastes YOY"), 
         month = map_chr(date, ~month.name[lubridate::month(.x)]), 
         `seagrass/unvegetated` = map_chr(`seagrass/unvegetated`, capitalize)) %>%
  filter(month %in% c("April", "May"))

seine_data %>% 
  group_by(`seagrass/unvegetated`, year, site_name) %>% 
  summarise(count = length(unique(seine_id))) %>% 
  spread(`seagrass/unvegetated`, count) %>%
  knitr::kable()
```

# Abundance

## Bar Chart

```{r abundance_plot, fig.height = 4, fig.width = 8}
seine_count_data <- 
  seine_data %>% 
  group_by(year, site_name, `seagrass/unvegetated`,
           seine_id, distance_m, spec_binomial) %>% 
  summarise(count = n()) %>% ungroup() %>% 
  complete(nesting(year, site_name, `seagrass/unvegetated`,
           seine_id, distance_m), spec_binomial, fill = list(count = 0)) %>% 
  separate(spec_binomial, c("genus", "species"), sep = " ") %>% 
  mutate(density = count/distance_m) %>% 
  rename(seagrass_unvegetated = `seagrass/unvegetated`)

seine_summary <- 
  seine_count_data %>% 
  group_by(year, site_name, seagrass_unvegetated, seine_id) %>%
  summarize(density = sum(density)) %>% ungroup() %>%
  group_by(site_name, seagrass_unvegetated) %>% 
  summarize(se = sd(density)/sqrt(n()), 
            density = mean(density)) %>% 
  complete(site_name, seagrass_unvegetated)

seine_summary %>% 
  ggplot(aes(seagrass_unvegetated, density)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", 
           fill = "grey60", size = 1) + 
  geom_errorbar(aes(ymin = density - se, ymax = density + se),
                position = position_dodge(width = 0.8), 
                width = 0.4, size = 1.2) + 
  scale_y_continuous(expand = c(0,0), breaks = seq(0,12,2),
                     limits = c(0, with(seine_summary, max(density + se + 1, na.rm = TRUE)))) +
  lemon::facet_rep_wrap(~site_name, strip.position = "bottom") + 
  ylab(expression(paste("Fish Density (m"^{-1}, ")"))) + 
  theme_trawls + 
  coord_cartesian(clip = "off") +
  theme(axis.title.x = element_blank(),
        panel.spacing = unit(0, "lines")) 
```

## Abundance Model

```{r abundance_glm}
seine_count_lm_data <- 
  seine_count_data %>% 
  group_by(year, site_name, seagrass_unvegetated, seine_id, distance_m) %>% 
  summarize(count = sum(count)) %>% 
  ungroup() %>% 
  mutate(density = count/distance_m)

seine_count_model <- glm(density ~ site_name*seagrass_unvegetated,
                         data = seine_count_lm_data, 
                         family = Gamma(link = "log"))

seine_count_model %>% 
  car::Anova(test.statistic = "LR") %>% as.data.frame() %>% 
  rownames_to_column("term") %>% 
  mutate_if(is.numeric, round, digits = 3) %>%
  knitr::kable()
```

# Biomass

## Bar Chart

```{r biomass_plot, fig.height = 4, fig.width = 8}
seine_biomass_lm_data <- seine_data %>%  
  filter(!is.na(weight_g)) %>% # 1 bat ray (Myliobatis californica) observation
  group_by(year, site_name, `seagrass/unvegetated`, seine_id, distance_m) %>% 
  summarize(biomass = sum(weight_g)) %>% 
  ungroup() %>% 
  mutate(scaled_biomass = biomass/distance_m) %>% 
  rename("seagrass_unvegetated" = `seagrass/unvegetated`)

seine_biomass_summary <-
  seine_biomass_lm_data %>% 
  group_by(site_name, seagrass_unvegetated) %>% 
  summarize(mean = mean(scaled_biomass), 
            se = sd(scaled_biomass)/sqrt(n()),
            lower = mean - se, 
            upper = mean + se)
  
seine_biomass_summary %>% 
  ggplot(aes(seagrass_unvegetated, mean)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", 
           fill = "grey60", size = 1) + 
  geom_errorbar(aes(ymin = lower, ymax = upper),
                position = position_dodge(width = 0.8), 
                width = 0.4, size = 1.2) + 
  scale_y_continuous(expand = c(0,0), breaks = seq(0,130,20),
                     limits = c(0, max(seine_biomass_summary$upper + 5))) + 
  lemon::facet_rep_wrap(~site_name, strip.position = "bottom") + 
  ylab(expression(paste("Fish Biomass (g*m"^{-1}, ")"))) + 
  theme_trawls + 
  theme(axis.title.x = element_blank(), 
        panel.spacing = unit(0, "lines"))
```

## Biomass Model

```{r biomass_glm}
biomass_model <- glm(scaled_biomass ~ site_name*seagrass_unvegetated,
                     data = seine_biomass_lm_data, 
                     family = Gamma(link = "log"))

biomass_model %>% car::Anova(test = "LR") %>% as.data.frame() %>% 
  rownames_to_column("term") %>% 
  mutate_if(is.numeric, round, digits = 3) %>% 
  knitr::kable()
```


# Species Composition

## NMDS Plot

```{r nmds_run, results = "hide"}
## Convert data to wide-format species counts
seine_sp_data <- seine_data %>% 
  group_by(year, site_name, `seagrass/unvegetated`, seine_id, distance_m, spec_binomial) %>%
  summarise (Count = n()) %>% ungroup() %>% 
  mutate(density = Count/distance_m) %>% 
  dplyr::select(-Count) %>% 
  spread(spec_binomial, density, fill = 0) %>% 
  rename(seagrass_unvegetated = `seagrass/unvegetated`)

## Species matrix
seine_sp_matrix <- as.matrix(seine_sp_data[,6:23])
rownames(seine_sp_matrix) <- with(seine_sp_data, paste(seagrass_unvegetated, site_name))

## Bray-Curtis dissimiliarity matrix
seine_bray <- vegdist(seine_sp_matrix, method = "bray")

## Fit NMDS
seine_mds <- metaMDS(seine_bray, k = 2)

## Format data for plotting
mds_plot_data <- seine_mds$points
mds_rownames <- rownames(mds_plot_data) 
mds_plot_data <- as.data.frame(mds_plot_data, row.names =FALSE)
mds_plot_data$seagrass <- mds_rownames
nmds_colors <- RColorBrewer::brewer.pal(6, "Paired")[c(2, 6)]
```

```{r nmds_plot, fig.height = 4, fig.width = 8}
mds_plot_data %>% 
  separate(seagrass, c("seagrass", "site"), sep = " ", extra = "merge") %>% 
  ggplot(aes(MDS1, MDS2, fill = seagrass, pch = site)) +
  geom_point(size = 3, stroke = 1.5) +
  scale_fill_manual(values = nmds_colors) +
  scale_shape_manual(values=c(21, 24)) + theme_bw() +
  labs(x = "NMDS1", y = "NMDS2", fill = "habitat") +
  theme_trawls + 
  cowplot::panel_border("black", 1) + 
  coord_cartesian(clip = "off") + 
  guides(fill=guide_legend(override.aes=list(shape=21)))
```


## PERMANOVA

## SIMPER
